"""add marzban credentials to servers

Revision ID: 06b8099910b2
Revises: 9a34eb5fe0fd
Create Date: 2026-07-29 00:39:52.611018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b8099910b2'
down_revision: Union[str, Sequence[str], None] = '9a34eb5fe0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('marzban_username', sa.String(length=100), nullable=True))
    op.add_column('servers', sa.Column('marzban_password_encrypted', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'marzban_password_encrypted')
    op.drop_column('servers', 'marzban_username')
    # ### end Alembic commands ###
