"""remove legacy vpn subscription fields

Revision ID: 106056414d7a
Revises: c98847d4749c
Create Date: 2026-07-29 21:24:30.530758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106056414d7a'
down_revision: Union[str, Sequence[str], None] = 'c98847d4749c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vpn_subscriptions_marzban_username'), table_name='vpn_subscriptions')
    op.drop_index(op.f('ix_vpn_subscriptions_server_id'), table_name='vpn_subscriptions')
    op.drop_constraint(op.f('vpn_subscriptions_vpn_uuid_key'), 'vpn_subscriptions', type_='unique')
    op.drop_constraint(op.f('fk_vpn_subscriptions_server_id'), 'vpn_subscriptions', type_='foreignkey')
    op.drop_column('vpn_subscriptions', 'server_id')
    op.drop_column('vpn_subscriptions', 'vless_link')
    op.drop_column('vpn_subscriptions', 'subscription_url')
    op.drop_column('vpn_subscriptions', 'marzban_username')
    op.drop_column('vpn_subscriptions', 'vpn_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_subscriptions', sa.Column('vpn_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('vpn_subscriptions', sa.Column('marzban_username', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('vpn_subscriptions', sa.Column('subscription_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('vpn_subscriptions', sa.Column('vless_link', sa.VARCHAR(length=2048), autoincrement=False, nullable=False))
    op.add_column('vpn_subscriptions', sa.Column('server_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_vpn_subscriptions_server_id'), 'vpn_subscriptions', 'servers', ['server_id'], ['id'])
    op.create_unique_constraint(op.f('vpn_subscriptions_vpn_uuid_key'), 'vpn_subscriptions', ['vpn_uuid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_vpn_subscriptions_server_id'), 'vpn_subscriptions', ['server_id'], unique=False)
    op.create_index(op.f('ix_vpn_subscriptions_marzban_username'), 'vpn_subscriptions', ['marzban_username'], unique=True)
    # ### end Alembic commands ###
