"""add public token to vpn subscriptions

Revision ID: 43ef87e39396
Revises: 106056414d7a
Create Date: 2026-07-30 06:24:45.884427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid

from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision: str = '43ef87e39396'
down_revision: Union[str, Sequence[str], None] = '106056414d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "vpn_subscriptions",
        sa.Column(
            "public_token",
            sa.Uuid(),
            nullable=True,
        ),
    )

    connection = op.get_bind()

    subscriptions = connection.execute(
        sa.text(
            """
            SELECT id
            FROM vpn_subscriptions
            WHERE public_token IS NULL
            """
        )
    ).fetchall()

    for subscription in subscriptions:
        connection.execute(
            sa.text(
                """
                UPDATE vpn_subscriptions
                SET public_token = :public_token
                WHERE id = :subscription_id
                """
            ),
            {
                "public_token": str(uuid.uuid4()),
                "subscription_id": subscription.id,
            },
        )

    op.alter_column(
        "vpn_subscriptions",
        "public_token",
        existing_type=sa.Uuid(),
        nullable=False,
    )

    op.create_unique_constraint(
        "uq_vpn_subscriptions_public_token",
        "vpn_subscriptions",
        ["public_token"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vpn_subscriptions', type_='unique')
    op.drop_column('vpn_subscriptions', 'public_token')
    # ### end Alembic commands ###
