"""add vpn subscription servers

Revision ID: c98847d4749c
Revises: 06b8099910b2
Create Date: 2026-07-29 01:45:54.738552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98847d4749c'
down_revision: Union[str, Sequence[str], None] = '06b8099910b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vpn_subscription_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('marzban_username', sa.String(length=64), nullable=False),
    sa.Column('vpn_uuid', sa.String(length=64), nullable=False),
    sa.Column('subscription_url', sa.String(length=512), nullable=False),
    sa.Column('vless_link', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['vpn_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vpn_subscription_servers_id'), 'vpn_subscription_servers', ['id'], unique=False)
    op.create_index(op.f('ix_vpn_subscription_servers_server_id'), 'vpn_subscription_servers', ['server_id'], unique=False)
    op.create_index(op.f('ix_vpn_subscription_servers_subscription_id'), 'vpn_subscription_servers', ['subscription_id'], unique=False)
    op.drop_column('servers', 'marzban_username')
    op.drop_column('servers', 'marzban_password_encrypted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('marzban_password_encrypted', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('servers', sa.Column('marzban_username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vpn_subscription_servers_subscription_id'), table_name='vpn_subscription_servers')
    op.drop_index(op.f('ix_vpn_subscription_servers_server_id'), table_name='vpn_subscription_servers')
    op.drop_index(op.f('ix_vpn_subscription_servers_id'), table_name='vpn_subscription_servers')
    op.drop_table('vpn_subscription_servers')
    # ### end Alembic commands ###
